name: Jira Issue Type Updater
description: Change issue type of specific Jira issue
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to update issue type
    required: true
  issueTypeName:
    description: The issueTypeName to apply to the issue, e.g. 'Story'
    required: false
  issueTypeId:
    description: The issueTypeId (issue type id) to apply to the issue 
    required: false
runs:
  using: 'node12'
  main: './dist/index.js'
